Added a new step to replace the 'BUILD_BADGE_PLACEHOLDER' in README with the actual build status badge.
To achieve that, we'll need to share the status of tests' results across jobs.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -53,12 +53,18 @@ jobs:
           newman --version
 
       - name: Run Postman tests with Newman
+        id: test-results # id is used later on to check whether tests passed or failed
         run: |
           newman run ${{ env.POSTMAN_COLLECTION }} \
             -e ${{ env.POSTMAN_ENVIRONMENT }} \
             --reporters cli,html,junit \
             --reporter-html-export ${{ env.NEWMAN_HTML_REPORT_FILE }} \
             --reporter-junit-export ${{ env.NEWMAN_XML_REPORT_FILE }}
+          if [ $? -eq 0 ]; then
+            echo "outcome=success" >> $GITHUB_OUTPUT
+          else
+            echo "outcome=failure" >> $GITHUB_OUTPUT
+          fi
 
       - name: Upload the content for GitHub Pages
         uses: actions/upload-artifact@v4
@@ -96,6 +102,23 @@ jobs:
 
       - name: Set SITE_ROOT_URL Variable
         run: echo "SITE_ROOT_URL=https://${GITHUB_ACTOR}.github.io/${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
+
+      - name: Update README with dynamic badge status
+        run: |
+          # Determine badge status based on test result outcome
+          if [ "${{ needs.build.outputs.test_outcome }}" == "success" ]; then
+            BADGE="passing-brightgreen"
+          else
+            BADGE="failing-red"
+          fi
+          
+          # Construct the badge Markdown with full path to the report
+          BADGE_MARKDOWN="[![Build Status](https://img.shields.io/badge/build-${BADGE})](${{ env.SITE_ROOT_URL }}/${{ env.NEWMAN_HTML_REPORT_FILE }})"
+
+          echo "Badge MARKDOWN: ${BADGE_MARKDOWN}"
+          
+          # Update the README.md file with the badge
+          sed -i "s|<!-- BUILD_BADGE_PLACEHOLDER -->|${BADGE_MARKDOWN}|g" "${{ env.PAGES_FOLDER }}/README.md"
 
       - name: Deploy to GitHub Pages 🚀
         uses: JamesIves/github-pages-deploy-action@v4
