Committing everything

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -21,7 +21,8 @@ env:
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   POSTMAN_COLLECTION: postman/sample.json
   REPO_NAME: ${{ github.event.repository.name }}
-#  POSTMAN_COLLECTION: postman/keycloak-postman-collection.json
+  SITE_ROOT_URL: https://$GITHUB_ACTOR.github.io/${{ env.REPO_NAME }}
+  #  POSTMAN_COLLECTION: postman/keycloak-postman-collection.json
   POSTMAN_ENVIRONMENT: postman/keycloak-local.postman_environment.json
 
 jobs:
@@ -65,87 +66,87 @@ jobs:
             echo "Postman environment not found!" && exit 1
           fi
 
-#      - name: Install Docker with specific version
-#        run: |
-#          # Step 1: Update package index and install dependencies
-#          sudo apt-get update
-#          sudo apt-get install -y \
-#            ca-certificates \
-#            curl \
-#            gnupg \
-#            lsb-release
-#
-#          # Step 2: Add Docker's official GPG key
-#          sudo mkdir -m 0755 -p /etc/apt/keyrings
-#          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
-#            sudo tee /etc/apt/keyrings/docker.asc > /dev/null
-#
-#          # Step 3: Add Docker's official repository
-#          echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] \
-#            https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | \
-#            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
-#
-#          # Step 4: Update package index again and install Docker using the Docker installation script
-#          sudo apt-get update
-#          curl -fsSL https://get.docker.com | VERSION=${DOCKER_VERSION}
-#
-#          # Step 5: Verify Docker installation
-#          docker --version
-#
-#      - name: Install Docker Compose with specific version
-#        run: |
-#          sudo curl -L "https://github.com/docker/compose/releases/download/v${{ env.DOCKER_COMPOSE_VERSION }}/docker-compose-$(uname -s)-$(uname -m)" \
-#            -o /usr/local/bin/docker-compose
-#          sudo chmod +x /usr/local/bin/docker-compose
-#          docker-compose --version
-#
-#
-#      - name: Build and run services using start.sh script
-#        run: |
-#          chmod +x ${{ env.DOCKER_COMPOSE_DIR }}/startup_helper.sh
-#          chmod +x ${{ env.DOCKER_COMPOSE_DIR }}/keycloak/start.sh
-#          # Check if docker-compose is available before running the start.sh script
-#          which docker-compose || { echo "docker-compose is not installed or not in PATH"; exit 1; }
-#          cd ${{ env.DOCKER_COMPOSE_DIR }}/keycloak
-#          ./start.sh
+      #      - name: Install Docker with specific version
+      #        run: |
+      #          # Step 1: Update package index and install dependencies
+      #          sudo apt-get update
+      #          sudo apt-get install -y \
+      #            ca-certificates \
+      #            curl \
+      #            gnupg \
+      #            lsb-release
+      #
+      #          # Step 2: Add Docker's official GPG key
+      #          sudo mkdir -m 0755 -p /etc/apt/keyrings
+      #          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
+      #            sudo tee /etc/apt/keyrings/docker.asc > /dev/null
+      #
+      #          # Step 3: Add Docker's official repository
+      #          echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] \
+      #            https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | \
+      #            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
+      #
+      #          # Step 4: Update package index again and install Docker using the Docker installation script
+      #          sudo apt-get update
+      #          curl -fsSL https://get.docker.com | VERSION=${DOCKER_VERSION}
+      #
+      #          # Step 5: Verify Docker installation
+      #          docker --version
+      #
+      #      - name: Install Docker Compose with specific version
+      #        run: |
+      #          sudo curl -L "https://github.com/docker/compose/releases/download/v${{ env.DOCKER_COMPOSE_VERSION }}/docker-compose-$(uname -s)-$(uname -m)" \
+      #            -o /usr/local/bin/docker-compose
+      #          sudo chmod +x /usr/local/bin/docker-compose
+      #          docker-compose --version
+      #
+      #
+      #      - name: Build and run services using start.sh script
+      #        run: |
+      #          chmod +x ${{ env.DOCKER_COMPOSE_DIR }}/startup_helper.sh
+      #          chmod +x ${{ env.DOCKER_COMPOSE_DIR }}/keycloak/start.sh
+      #          # Check if docker-compose is available before running the start.sh script
+      #          which docker-compose || { echo "docker-compose is not installed or not in PATH"; exit 1; }
+      #          cd ${{ env.DOCKER_COMPOSE_DIR }}/keycloak
+      #          ./start.sh
 
       - name: Install Newman with specific version
         run: |
           npm install -g newman@${{ env.NEWMAN_VERSION }} newman-reporter-html
           newman --version
 
-#      - name: Wait for service to be available
-#        run: |
-#          max_retries=10  # Set the max number of retries
-#          count=0
-#          until [ $count -ge $max_retries ]
-#          do
-#            response=$(curl -s http://localhost:9000/health/ready)
-#            if [[ "$response" == *'"status": "UP"'* ]]; then
-#              echo "Service is up!"
-#              break
-#            fi
-#            count=$((count+1))
-#            echo "Waiting for service to start... Attempt $count/$max_retries"
-#            sleep 10
-#          done
-#
-#          if [ $count -ge $max_retries ]; then
-#            echo "Service did not start in time. Exiting."
-#            exit 1  # Fail the job if the service is not available after retries
-#          fi
-#
-#      - name: Collect Docker container logs
-#        run: |
-#          # Loop through each container and print logs with a container-specific prefix
-#          for container in mailhog keycloak openldap keycloak-db realm-export-generator keycloak_setup; do
-#            echo "---- Logs for $container ----"
-#
-#            # Display the logs for the current container, prefixing each line with the container name for clarity
-#            docker logs "$container" | sed "s/^/[$container] /"
-#
-#            echo "---- End of logs for $container ----"
-#          done
+      #      - name: Wait for service to be available
+      #        run: |
+      #          max_retries=10  # Set the max number of retries
+      #          count=0
+      #          until [ $count -ge $max_retries ]
+      #          do
+      #            response=$(curl -s http://localhost:9000/health/ready)
+      #            if [[ "$response" == *'"status": "UP"'* ]]; then
+      #              echo "Service is up!"
+      #              break
+      #            fi
+      #            count=$((count+1))
+      #            echo "Waiting for service to start... Attempt $count/$max_retries"
+      #            sleep 10
+      #          done
+      #
+      #          if [ $count -ge $max_retries ]; then
+      #            echo "Service did not start in time. Exiting."
+      #            exit 1  # Fail the job if the service is not available after retries
+      #          fi
+      #
+      #      - name: Collect Docker container logs
+      #        run: |
+      #          # Loop through each container and print logs with a container-specific prefix
+      #          for container in mailhog keycloak openldap keycloak-db realm-export-generator keycloak_setup; do
+      #            echo "---- Logs for $container ----"
+      #
+      #            # Display the logs for the current container, prefixing each line with the container name for clarity
+      #            docker logs "$container" | sed "s/^/[$container] /"
+      #
+      #            echo "---- End of logs for $container ----"
+      #          done
 
       - name: Run Postman tests with Newman
         id: test-results # id is used later on to check whether tests passed or failed
@@ -165,21 +166,21 @@ jobs:
         run: |
           echo "### Postman Test Results" >> $GITHUB_STEP_SUMMARY
           echo "#### Test run completed, view summary after deployment." >> $GITHUB_STEP_SUMMARY
-          echo "#### HTML Report: [View HTML Report](https://$GITHUB_ACTOR.github.io/${{ env.REPO_NAME }}/${{ env.NEWMAN_REPORT_FILE }})" >> $GITHUB_STEP_SUMMARY
-          echo "#### XML Report: [View XML Report](https://$GITHUB_ACTOR.github.io/${{ env.REPO_NAME }}/postman-report.xml)" >> $GITHUB_STEP_SUMMARY
+          echo "#### HTML Report: [View HTML Report](${{ SITE_ROOT_URL }}/${{ env.NEWMAN_REPORT_FILE }})" >> $GITHUB_STEP_SUMMARY
+          echo "#### XML Report: [View XML Report](${{ SITE_ROOT_URL }}/postman-report.xml)" >> $GITHUB_STEP_SUMMARY
+      
 
-
-     #      - name: Collect Docker container logs
-#        run: |
-#          # Loop through each container and print logs with a container-specific prefix
-#          for container in mailhog keycloak openldap keycloak-db realm-export-generator keycloak_setup; do
-#            echo "---- Logs for $container ----"
-#
-#            # Display the logs for the current container, prefixing each line with the container name for clarity
-#            docker logs "$container" | sed "s/^/[$container] /"
-#
-#            echo "---- End of logs for $container ----"
-#          done
+      #      - name: Collect Docker container logs
+      #        run: |
+      #          # Loop through each container and print logs with a container-specific prefix
+      #          for container in mailhog keycloak openldap keycloak-db realm-export-generator keycloak_setup; do
+      #            echo "---- Logs for $container ----"
+      #
+      #            # Display the logs for the current container, prefixing each line with the container name for clarity
+      #            docker logs "$container" | sed "s/^/[$container] /"
+      #
+      #            echo "---- End of logs for $container ----"
+      #          done
 
       - name: Upload the content for GitHub Pages
         uses: actions/upload-artifact@v4 #v3 - Error: Unable to find any artifacts for the associated workflow
@@ -193,34 +194,28 @@ jobs:
     name: gh-pages-deployment
     runs-on: ubuntu-latest
     needs: build
-  
+
     permissions:
       contents: write
-  
-    env:
-      ARTIFACT_NAME: artifact.tar
-      REPO_NAME: ${{ github.repository }}
-      GITHUB_ACTOR: ${{ github.actor }}
-      GITHUB_URL: https://${{ github.actor }}.github.io/${{ github.repository }}
-  
+
     steps:
       - name: Checkout the Repository 🛎️
         uses: actions/checkout@v4
-      
+
       - name: Download GitHub Pages Artifact 📦
         uses: actions/download-artifact@v4
         with:
           name: ${{ env.PAGES_FOLDER }}
           path: ${{ env.PAGES_FOLDER }}
-      
+
       - name: Check Contents of the Directory 📂
         run: |
           ls -R .
-      
+
       - name: Copy README to GitHub Pages Folder
         run: |
           cp README.md ${{ env.PAGES_FOLDER }}/README.md
-      
+
       - name: Update README with dynamic badge status
         run: |
           # Determine badge status based on test result outcome
@@ -229,21 +224,21 @@ jobs:
           else
             BADGE="failing-red"
           fi
-      
-          # Construct the badge URL with full path to the report
-          BADGE_URL="https://img.shields.io/badge/build-${BADGE}?url=https://$GITHUB_ACTOR.github.io/${{ env.REPO_NAME }}/${{ env.NEWMAN_REPORT_FILE }}"
-          echo "Badge URL: ${BADGE_URL}"
+          
+          # Construct the badge Markdown with full path to the report
+          BADGE_MARKDOWN=[![Build Status](https://img.shields.io/badge/build-${BADGE})](${{ SITE_ROOT_URL }}/${{ env.NEWMAN_REPORT_FILE }})
+          echo "Badge MARKDOWN: ${BADGE_MARKDOWN}"
           # Update the copied README.md file with the badge
-          sed -i "s|<!-- BUILD_BADGE_PLACEHOLDER -->|![Build Status](${BADGE_URL})|g" ${{ env.PAGES_FOLDER }}/README.md
+          sed -i "s|<!-- BUILD_BADGE_PLACEHOLDER -->|${BADGE_MARKDOWN}|g" ${{ env.PAGES_FOLDER }}/README.md
 
       - name: Deploy to GitHub Pages 🚀
         uses: JamesIves/github-pages-deploy-action@v4
         with:
-          folder:  ${{ env.PAGES_FOLDER }}
-      
+          folder: ${{ env.PAGES_FOLDER }}
+
       - name: Display GitHub Pages URL 🌐
         run: |
-          echo "The GitHub Pages URL is: ${{ env.GITHUB_URL }}"
+          echo "The GitHub Pages URL is: ${{ env.SITE_ROOT_URL }}"
 
   post-deploy-summary:
     runs-on: ubuntu-latest
