Committing everything

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -151,6 +151,12 @@ jobs:
             --reporters cli,html,junit \
             --reporter-html-export ${{ env.NEWMAN_REPORT_FILE }} \
             --reporter-junit-export junit-report.xml
+          # Capture the outcome
+          if [ $? -eq 0 ]; then
+            echo "::set-output name=outcome::success"
+          else
+            echo "::set-output name=outcome::failure"
+          fi
 
 #      - name: Run Postman tests
 #        id: test-results
@@ -160,21 +166,6 @@ jobs:
 #          --reporter-html-export ${{ env.NEWMAN_REPORT_FILE }} \
 #          --reporter-junit-export junit-report.xml
 #          echo "REPORT_FILE=${{ env.NEWMAN_REPORT_FILE }}" >> $GITHUB_ENV  # Save the report path to an environment variable
-
-      - name: Update README with dynamic badge status
-        if: always()  # This ensures the step runs regardless of test pass/fail
-        run: |
-          echo "Test Outcome: ${{ steps.test-results.outcome }}"
-          if [ "${{ steps.test-results.outcome }}" == "success" ]; then
-            echo "[[[[[[[[[[[[[[[[[[[[[[["
-            echo "![Test Results](https://img.shields.io/badge/build-passing-brightgreen?url=https://$GITHUB_ACTOR.github.io/${{ github.repository }}/postman-report.html)" > temp.md
-          else
-            echo "[[[[[[[[[[[[[[[[[[[[[[[-----------------"
-            echo "![Build Status](https://img.shields.io/badge/build-failing-red?url=https://$GITHUB_ACTOR.github.io/${{ github.repository }}/postman-report.html)" > temp.md
-          fi
-          cat README.md >> temp.md  # Append existing README to temp.md
-          mv temp.md README.md  # Replace README.md with updated content
-
 
       #      - name: Collect Docker container logs
 #        run: |
@@ -194,6 +185,28 @@ jobs:
           name: postman-test-report
           path: ${{ env.NEWMAN_REPORT_FILE }}
 
+      - name: Set up Git for GitHub Pages
+        run: |
+          git status
+          git config --global user.name "GitHub Actions"
+          git config --global user.email "actions@github.com"
+          git fetch origin  # Fetch the latest branches
+          git checkout -b gh-pages  # Switch to gh-pages branch
+
+      - name: Update README with dynamic badge status
+        if: always()  # This ensures the step runs regardless of test pass/fail
+        run: |
+          echo "Test Outcome: ${{ steps.test-results.outcome }}"
+          if [ "${{ steps.test-results.outcome }}" == "success" ]; then
+            echo "[[[[[[[[[[[[[[[[[[[[[[["
+            echo "![Test Results](https://img.shields.io/badge/build-passing-brightgreen?url=https://$GITHUB_ACTOR.github.io/${{ github.repository }}/postman-report.html)" > temp.md
+          else
+            echo "[[[[[[[[[[[[[[[[[[[[[[[-----------------"
+            echo "![Build Status](https://img.shields.io/badge/build-failing-red?url=https://$GITHUB_ACTOR.github.io/${{ github.repository }}/postman-report.html)" > temp.md
+          fi
+          cat README.md >> temp.md  # Append existing README to temp.md
+          mv temp.md README.md  # Replace README.md with updated content
+
 #      - name: Generate and move Postman test report to GitHub Pages folder
 #        run: |
 #          mkdir -p gh-pages  # Create gh-pages folder if it doesn't exist
@@ -212,14 +225,6 @@ jobs:
 #          git add gh-pages/postman-report.html
 #          git commit -m "Add Postman test report"
 #          git push origin gh-pages
-
-      - name: Set up Git for GitHub Pages
-        run: |
-          git status
-          git config --global user.name "GitHub Actions"
-          git config --global user.email "actions@github.com"
-          git fetch origin  # Fetch the latest branches
-          git checkout gh-pages || git checkout -b gh-pages  # Switch to gh-pages branch or create it if it doesn't exist
 
       - name: Generate and move Postman test report to GitHub Pages root
         run: |
