Committing everything

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -19,7 +19,8 @@ env:
   NEWMAN_REPORT_FILE: postman-report.html
   DOCKER_COMPOSE_FILE: docker-compose.yml
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  POSTMAN_COLLECTION: postman/keycloak-postman-collection.json
+  POSTMAN_COLLECTION: postman/sample.json
+#  POSTMAN_COLLECTION: postman/keycloak-postman-collection.json
   POSTMAN_ENVIRONMENT: postman/keycloak-local.postman_environment.json
 
 jobs:
@@ -61,87 +62,87 @@ jobs:
             echo "Postman environment not found!" && exit 1
           fi
 
-      - name: Install Docker with specific version
-        run: |
-          # Step 1: Update package index and install dependencies
-          sudo apt-get update
-          sudo apt-get install -y \
-            ca-certificates \
-            curl \
-            gnupg \
-            lsb-release
-
-          # Step 2: Add Docker's official GPG key
-          sudo mkdir -m 0755 -p /etc/apt/keyrings
-          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
-            sudo tee /etc/apt/keyrings/docker.asc > /dev/null
-
-          # Step 3: Add Docker's official repository
-          echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] \
-            https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | \
-            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
-
-          # Step 4: Update package index again and install Docker using the Docker installation script
-          sudo apt-get update
-          curl -fsSL https://get.docker.com | VERSION=${DOCKER_VERSION}
-
-          # Step 5: Verify Docker installation
-          docker --version
-
-      - name: Install Docker Compose with specific version
-        run: |
-          sudo curl -L "https://github.com/docker/compose/releases/download/v${{ env.DOCKER_COMPOSE_VERSION }}/docker-compose-$(uname -s)-$(uname -m)" \
-            -o /usr/local/bin/docker-compose
-          sudo chmod +x /usr/local/bin/docker-compose
-          docker-compose --version
-      
-
-      - name: Build and run services using start.sh script
-        run: |
-          chmod +x ${{ env.DOCKER_COMPOSE_DIR }}/startup_helper.sh
-          chmod +x ${{ env.DOCKER_COMPOSE_DIR }}/keycloak/start.sh
-          # Check if docker-compose is available before running the start.sh script
-          which docker-compose || { echo "docker-compose is not installed or not in PATH"; exit 1; }
-          cd ${{ env.DOCKER_COMPOSE_DIR }}/keycloak
-          ./start.sh
+#      - name: Install Docker with specific version
+#        run: |
+#          # Step 1: Update package index and install dependencies
+#          sudo apt-get update
+#          sudo apt-get install -y \
+#            ca-certificates \
+#            curl \
+#            gnupg \
+#            lsb-release
+#
+#          # Step 2: Add Docker's official GPG key
+#          sudo mkdir -m 0755 -p /etc/apt/keyrings
+#          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
+#            sudo tee /etc/apt/keyrings/docker.asc > /dev/null
+#
+#          # Step 3: Add Docker's official repository
+#          echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] \
+#            https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | \
+#            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
+#
+#          # Step 4: Update package index again and install Docker using the Docker installation script
+#          sudo apt-get update
+#          curl -fsSL https://get.docker.com | VERSION=${DOCKER_VERSION}
+#
+#          # Step 5: Verify Docker installation
+#          docker --version
+#
+#      - name: Install Docker Compose with specific version
+#        run: |
+#          sudo curl -L "https://github.com/docker/compose/releases/download/v${{ env.DOCKER_COMPOSE_VERSION }}/docker-compose-$(uname -s)-$(uname -m)" \
+#            -o /usr/local/bin/docker-compose
+#          sudo chmod +x /usr/local/bin/docker-compose
+#          docker-compose --version
+#
+#
+#      - name: Build and run services using start.sh script
+#        run: |
+#          chmod +x ${{ env.DOCKER_COMPOSE_DIR }}/startup_helper.sh
+#          chmod +x ${{ env.DOCKER_COMPOSE_DIR }}/keycloak/start.sh
+#          # Check if docker-compose is available before running the start.sh script
+#          which docker-compose || { echo "docker-compose is not installed or not in PATH"; exit 1; }
+#          cd ${{ env.DOCKER_COMPOSE_DIR }}/keycloak
+#          ./start.sh
 
       - name: Install Newman with specific version
         run: |
           npm install -g newman@${{ env.NEWMAN_VERSION }} newman-reporter-html
           newman --version
 
-      - name: Wait for service to be available
-        run: |
-          max_retries=10  # Set the max number of retries
-          count=0
-          until [ $count -ge $max_retries ]
-          do
-            response=$(curl -s http://localhost:9000/health/ready)
-            if [[ "$response" == *'"status": "UP"'* ]]; then
-              echo "Service is up!"
-              break
-            fi
-            count=$((count+1))
-            echo "Waiting for service to start... Attempt $count/$max_retries"
-            sleep 10
-          done
-          
-          if [ $count -ge $max_retries ]; then
-            echo "Service did not start in time. Exiting."
-            exit 1  # Fail the job if the service is not available after retries
-          fi
-
-      - name: Collect Docker container logs
-        run: |
-          # Loop through each container and print logs with a container-specific prefix
-          for container in mailhog keycloak openldap keycloak-db realm-export-generator keycloak_setup; do
-            echo "---- Logs for $container ----"
-
-            # Display the logs for the current container, prefixing each line with the container name for clarity
-            docker logs "$container" | sed "s/^/[$container] /"
-
-            echo "---- End of logs for $container ----"
-          done
+#      - name: Wait for service to be available
+#        run: |
+#          max_retries=10  # Set the max number of retries
+#          count=0
+#          until [ $count -ge $max_retries ]
+#          do
+#            response=$(curl -s http://localhost:9000/health/ready)
+#            if [[ "$response" == *'"status": "UP"'* ]]; then
+#              echo "Service is up!"
+#              break
+#            fi
+#            count=$((count+1))
+#            echo "Waiting for service to start... Attempt $count/$max_retries"
+#            sleep 10
+#          done
+#
+#          if [ $count -ge $max_retries ]; then
+#            echo "Service did not start in time. Exiting."
+#            exit 1  # Fail the job if the service is not available after retries
+#          fi
+#
+#      - name: Collect Docker container logs
+#        run: |
+#          # Loop through each container and print logs with a container-specific prefix
+#          for container in mailhog keycloak openldap keycloak-db realm-export-generator keycloak_setup; do
+#            echo "---- Logs for $container ----"
+#
+#            # Display the logs for the current container, prefixing each line with the container name for clarity
+#            docker logs "$container" | sed "s/^/[$container] /"
+#
+#            echo "---- End of logs for $container ----"
+#          done
 
       - name: Run Postman tests with Newman
         run: |
@@ -151,17 +152,17 @@ jobs:
             --reporter-html-export ${{ env.NEWMAN_REPORT_FILE }} \
             --reporter-junit-export junit-report.xml
 
-      - name: Collect Docker container logs
-        run: |
-          # Loop through each container and print logs with a container-specific prefix
-          for container in mailhog keycloak openldap keycloak-db realm-export-generator keycloak_setup; do
-            echo "---- Logs for $container ----"
-
-            # Display the logs for the current container, prefixing each line with the container name for clarity
-            docker logs "$container" | sed "s/^/[$container] /"
-
-            echo "---- End of logs for $container ----"
-          done
+#      - name: Collect Docker container logs
+#        run: |
+#          # Loop through each container and print logs with a container-specific prefix
+#          for container in mailhog keycloak openldap keycloak-db realm-export-generator keycloak_setup; do
+#            echo "---- Logs for $container ----"
+#
+#            # Display the logs for the current container, prefixing each line with the container name for clarity
+#            docker logs "$container" | sed "s/^/[$container] /"
+#
+#            echo "---- End of logs for $container ----"
+#          done
 
       - name: Upload Postman test report as artifact
         uses: actions/upload-artifact@v3
@@ -181,12 +182,12 @@ jobs:
 #          echo "[View Test Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> README.md
 
 
-      - name: Clean up Docker containers and volumes
-        run: |
-          # Explicit check for docker-compose before using it
-          which docker-compose || { echo "docker-compose is not installed or not in PATH"; exit 1; }
-          cd ${{ env.DOCKER_COMPOSE_DIR }}/keycloak
-          docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} down --volumes --remove-orphans
+#      - name: Clean up Docker containers and volumes
+#        run: |
+#          # Explicit check for docker-compose before using it
+#          which docker-compose || { echo "docker-compose is not installed or not in PATH"; exit 1; }
+#          cd ${{ env.DOCKER_COMPOSE_DIR }}/keycloak
+#          docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} down --volumes --remove-orphans
 
       - name: Deploy README.md to GitHub Pages
         #        if: github.ref == 'refs/heads/main'  # Ensure this step only runs for the main branch
